### PR TITLE
Russian language support

### PR DESCRIPTION
**Pull request by ankar84**
Adding Russian language support.
I will continue to translate in a near future.

### CODE REVIEW

**Comment by ankar84** [comment]
@murtaza98 Hello!
I prepared Russian translate to your wonderful application!
Please consider to review and merge that.
Thank you!

**Comment by murtaza98** [comment]
Hi, @ankar84 Thanks for the valued contribution!! Truly appreciate it :blue_heart:  Please check out [this app release](https://github.com/AddReminders/Reminders-in-RocketChat/releases/tag/2.1.2) with your translations. Feel free to report any issues you see :smile:

**Comment by murtaza98** [comment]
Also, if possible, please let me know if all looks good in the above version wrt new Russian translations so I can submit this version to the Rocket.Chat's marketplace as well :smile:

**Comment by ankar84** [comment]
> Also, if possible, please let me know if all looks good in the above version wrt new Russian translations so I can submit this version to the Rocket.Chat's marketplace as well 😄

Hey, @murtaza98 
Translate works perfect
image

About my translation quality - it's about 95%. I saw a few places to improve, but for now it's ready to market.

**Pull request merged**
